# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.18)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget xdr-static xdr-shared hdf-static hdf-shared mfhdf-static mfhdf-shared hdp hdp-shared hdfimport hdfimport-shared hdiff hdiff-shared hrepack hrepack-shared)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target xdr-static
add_library(xdr-static STATIC IMPORTED)

set_target_properties(xdr-static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "N:/Development/Dev_Base/hdf-4.2.16/msvc/mfhdf/xdr;N:/Development/Dev_Base/hdf-4.2.16/mfhdf/xdr"
  INTERFACE_LINK_LIBRARIES "\$<\$<OR:\$<PLATFORM_ID:Windows>,\$<PLATFORM_ID:MinGW>>:ws2_32.lib>"
)

# Create imported target xdr-shared
add_library(xdr-shared SHARED IMPORTED)

set_target_properties(xdr-shared PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "H4_BUILT_AS_DYNAMIC_LIB=1"
  INTERFACE_INCLUDE_DIRECTORIES "N:/Development/Dev_Base/hdf-4.2.16/msvc/mfhdf/xdr;N:/Development/Dev_Base/hdf-4.2.16/mfhdf/xdr"
  INTERFACE_LINK_LIBRARIES "\$<\$<OR:\$<PLATFORM_ID:Windows>,\$<PLATFORM_ID:MinGW>>:ws2_32.lib>"
)

# Create imported target hdf-static
add_library(hdf-static STATIC IMPORTED)

set_target_properties(hdf-static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "N:/Development/Dev_Base/hdf-4.2.16/msvc/hdf/src;N:/Development/Dev_Base/hdf-4.2.16/hdf/src"
  INTERFACE_LINK_LIBRARIES "N:/Development/Dev_Base/jpeg-9c/vc143/x64/vs2022_Release/jpeg.lib;N:/Development/Dev_Base/zlib-1.2.11/vc143/x64/vs2022_Release/zlib.lib"
)

# Create imported target hdf-shared
add_library(hdf-shared SHARED IMPORTED)

set_target_properties(hdf-shared PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "H4_BUILT_AS_DYNAMIC_LIB=1"
  INTERFACE_INCLUDE_DIRECTORIES "N:/Development/Dev_Base/hdf-4.2.16/msvc/hdf/src;N:/Development/Dev_Base/hdf-4.2.16/hdf/src"
)

# Create imported target mfhdf-static
add_library(mfhdf-static STATIC IMPORTED)

set_target_properties(mfhdf-static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "N:/Development/Dev_Base/hdf-4.2.16/msvc/mfhdf/libsrc;N:/Development/Dev_Base/hdf-4.2.16/mfhdf/libsrc"
  INTERFACE_LINK_LIBRARIES "xdr-static;hdf-static"
)

# Create imported target mfhdf-shared
add_library(mfhdf-shared SHARED IMPORTED)

set_target_properties(mfhdf-shared PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "H4_BUILT_AS_DYNAMIC_LIB=1"
  INTERFACE_INCLUDE_DIRECTORIES "N:/Development/Dev_Base/hdf-4.2.16/msvc/mfhdf/libsrc;N:/Development/Dev_Base/hdf-4.2.16/mfhdf/libsrc"
  INTERFACE_LINK_LIBRARIES "xdr-shared;hdf-shared"
)

# Create imported target hdp
add_executable(hdp IMPORTED)

# Create imported target hdp-shared
add_executable(hdp-shared IMPORTED)

# Create imported target hdfimport
add_executable(hdfimport IMPORTED)

# Create imported target hdfimport-shared
add_executable(hdfimport-shared IMPORTED)

# Create imported target hdiff
add_executable(hdiff IMPORTED)

# Create imported target hdiff-shared
add_executable(hdiff-shared IMPORTED)

# Create imported target hrepack
add_executable(hrepack IMPORTED)

# Create imported target hrepack-shared
add_executable(hrepack-shared IMPORTED)

# Import target "xdr-static" for configuration "Debug"
set_property(TARGET xdr-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(xdr-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/libxdr_D.lib"
  )

# Import target "xdr-shared" for configuration "Debug"
set_property(TARGET xdr-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(xdr-shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/xdr_D.lib"
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/xdr_D.dll"
  )

# Import target "hdf-static" for configuration "Debug"
set_property(TARGET hdf-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hdf-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/libhdf_D.lib"
  )

# Import target "hdf-shared" for configuration "Debug"
set_property(TARGET hdf-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hdf-shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/hdf_D.lib"
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/hdf_D.dll"
  )

# Import target "mfhdf-static" for configuration "Debug"
set_property(TARGET mfhdf-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(mfhdf-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/libmfhdf_D.lib"
  )

# Import target "mfhdf-shared" for configuration "Debug"
set_property(TARGET mfhdf-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(mfhdf-shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/mfhdf_D.lib"
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/mfhdf_D.dll"
  )

# Import target "hdp" for configuration "Debug"
set_property(TARGET hdp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hdp PROPERTIES
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/hdp.exe"
  )

# Import target "hdp-shared" for configuration "Debug"
set_property(TARGET hdp-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hdp-shared PROPERTIES
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/hdp-shared.exe"
  )

# Import target "hdfimport" for configuration "Debug"
set_property(TARGET hdfimport APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hdfimport PROPERTIES
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/hdfimport.exe"
  )

# Import target "hdfimport-shared" for configuration "Debug"
set_property(TARGET hdfimport-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hdfimport-shared PROPERTIES
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/hdfimport-shared.exe"
  )

# Import target "hdiff" for configuration "Debug"
set_property(TARGET hdiff APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hdiff PROPERTIES
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/hdiff.exe"
  )

# Import target "hdiff-shared" for configuration "Debug"
set_property(TARGET hdiff-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hdiff-shared PROPERTIES
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/hdiff-shared.exe"
  )

# Import target "hrepack" for configuration "Debug"
set_property(TARGET hrepack APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hrepack PROPERTIES
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/hrepack.exe"
  )

# Import target "hrepack-shared" for configuration "Debug"
set_property(TARGET hrepack-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hrepack-shared PROPERTIES
  IMPORTED_LOCATION_DEBUG "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Debug/hrepack-shared.exe"
  )

# Import target "xdr-static" for configuration "Release"
set_property(TARGET xdr-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(xdr-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/libxdr.lib"
  )

# Import target "xdr-shared" for configuration "Release"
set_property(TARGET xdr-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(xdr-shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/xdr.lib"
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/xdr.dll"
  )

# Import target "hdf-static" for configuration "Release"
set_property(TARGET hdf-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdf-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/libhdf.lib"
  )

# Import target "hdf-shared" for configuration "Release"
set_property(TARGET hdf-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdf-shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/hdf.lib"
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/hdf.dll"
  )

# Import target "mfhdf-static" for configuration "Release"
set_property(TARGET mfhdf-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(mfhdf-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/libmfhdf.lib"
  )

# Import target "mfhdf-shared" for configuration "Release"
set_property(TARGET mfhdf-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(mfhdf-shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/mfhdf.lib"
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/mfhdf.dll"
  )

# Import target "hdp" for configuration "Release"
set_property(TARGET hdp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdp PROPERTIES
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/hdp.exe"
  )

# Import target "hdp-shared" for configuration "Release"
set_property(TARGET hdp-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdp-shared PROPERTIES
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/hdp-shared.exe"
  )

# Import target "hdfimport" for configuration "Release"
set_property(TARGET hdfimport APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdfimport PROPERTIES
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/hdfimport.exe"
  )

# Import target "hdfimport-shared" for configuration "Release"
set_property(TARGET hdfimport-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdfimport-shared PROPERTIES
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/hdfimport-shared.exe"
  )

# Import target "hdiff" for configuration "Release"
set_property(TARGET hdiff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdiff PROPERTIES
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/hdiff.exe"
  )

# Import target "hdiff-shared" for configuration "Release"
set_property(TARGET hdiff-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdiff-shared PROPERTIES
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/hdiff-shared.exe"
  )

# Import target "hrepack" for configuration "Release"
set_property(TARGET hrepack APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hrepack PROPERTIES
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/hrepack.exe"
  )

# Import target "hrepack-shared" for configuration "Release"
set_property(TARGET hrepack-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hrepack-shared PROPERTIES
  IMPORTED_LOCATION_RELEASE "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/Release/hrepack-shared.exe"
  )

# Import target "xdr-static" for configuration "MinSizeRel"
set_property(TARGET xdr-static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(xdr-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/libxdr.lib"
  )

# Import target "xdr-shared" for configuration "MinSizeRel"
set_property(TARGET xdr-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(xdr-shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/xdr.lib"
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/xdr.dll"
  )

# Import target "hdf-static" for configuration "MinSizeRel"
set_property(TARGET hdf-static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hdf-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/libhdf.lib"
  )

# Import target "hdf-shared" for configuration "MinSizeRel"
set_property(TARGET hdf-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hdf-shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/hdf.lib"
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/hdf.dll"
  )

# Import target "mfhdf-static" for configuration "MinSizeRel"
set_property(TARGET mfhdf-static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(mfhdf-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/libmfhdf.lib"
  )

# Import target "mfhdf-shared" for configuration "MinSizeRel"
set_property(TARGET mfhdf-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(mfhdf-shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/mfhdf.lib"
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/mfhdf.dll"
  )

# Import target "hdp" for configuration "MinSizeRel"
set_property(TARGET hdp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hdp PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/hdp.exe"
  )

# Import target "hdp-shared" for configuration "MinSizeRel"
set_property(TARGET hdp-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hdp-shared PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/hdp-shared.exe"
  )

# Import target "hdfimport" for configuration "MinSizeRel"
set_property(TARGET hdfimport APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hdfimport PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/hdfimport.exe"
  )

# Import target "hdfimport-shared" for configuration "MinSizeRel"
set_property(TARGET hdfimport-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hdfimport-shared PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/hdfimport-shared.exe"
  )

# Import target "hdiff" for configuration "MinSizeRel"
set_property(TARGET hdiff APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hdiff PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/hdiff.exe"
  )

# Import target "hdiff-shared" for configuration "MinSizeRel"
set_property(TARGET hdiff-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hdiff-shared PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/hdiff-shared.exe"
  )

# Import target "hrepack" for configuration "MinSizeRel"
set_property(TARGET hrepack APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hrepack PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/hrepack.exe"
  )

# Import target "hrepack-shared" for configuration "MinSizeRel"
set_property(TARGET hrepack-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hrepack-shared PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/MinSizeRel/hrepack-shared.exe"
  )

# Import target "xdr-static" for configuration "RelWithDebInfo"
set_property(TARGET xdr-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(xdr-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/libxdr.lib"
  )

# Import target "xdr-shared" for configuration "RelWithDebInfo"
set_property(TARGET xdr-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(xdr-shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/xdr.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/xdr.dll"
  )

# Import target "hdf-static" for configuration "RelWithDebInfo"
set_property(TARGET hdf-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hdf-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/libhdf.lib"
  )

# Import target "hdf-shared" for configuration "RelWithDebInfo"
set_property(TARGET hdf-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hdf-shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/hdf.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/hdf.dll"
  )

# Import target "mfhdf-static" for configuration "RelWithDebInfo"
set_property(TARGET mfhdf-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(mfhdf-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/libmfhdf.lib"
  )

# Import target "mfhdf-shared" for configuration "RelWithDebInfo"
set_property(TARGET mfhdf-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(mfhdf-shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/mfhdf.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/mfhdf.dll"
  )

# Import target "hdp" for configuration "RelWithDebInfo"
set_property(TARGET hdp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hdp PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/hdp.exe"
  )

# Import target "hdp-shared" for configuration "RelWithDebInfo"
set_property(TARGET hdp-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hdp-shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/hdp-shared.exe"
  )

# Import target "hdfimport" for configuration "RelWithDebInfo"
set_property(TARGET hdfimport APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hdfimport PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/hdfimport.exe"
  )

# Import target "hdfimport-shared" for configuration "RelWithDebInfo"
set_property(TARGET hdfimport-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hdfimport-shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/hdfimport-shared.exe"
  )

# Import target "hdiff" for configuration "RelWithDebInfo"
set_property(TARGET hdiff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hdiff PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/hdiff.exe"
  )

# Import target "hdiff-shared" for configuration "RelWithDebInfo"
set_property(TARGET hdiff-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hdiff-shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/hdiff-shared.exe"
  )

# Import target "hrepack" for configuration "RelWithDebInfo"
set_property(TARGET hrepack APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hrepack PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/hrepack.exe"
  )

# Import target "hrepack-shared" for configuration "RelWithDebInfo"
set_property(TARGET hrepack-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hrepack-shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "N:/Development/Dev_Base/hdf-4.2.16/msvc/bin/RelWithDebInfo/hrepack-shared.exe"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
